# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_databasestats_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasestats',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
